AI Chatbot
ptcrealitylab/vuforia-spatial-edge-server pull request #1040
Opened 2024-04-11 19:34 UTC by Steve-KX-RL

1. Have a (somewhat) useable conversation with your Azure AI chatbot, after inputting the credentials.
2. Get a list of historical & new events from user-interface, to feed into AI chatbot.
3. Decide the category of user question (summary/debug/tool/pdf/tool content/not relevant), and give different answers based on that.
4. Also need user-interface and remote-operator to work.

2024-04-11 19:39 UTC, hobinjk-ptc requested changes

2024-04-11 19:39 UTC, hobinjk-ptc commented on server.js
> +    function parseCategory(result) {
This addition would be better organized if it were in its own file. One example of this is objectRouter and other routers defined above

2024-04-11 19:48 UTC, Steve-KX-RL commented on package-lock.json
Just realized I accidentally committed this file. Should I make another commit to revert it back to what it was before?

2024-04-11 19:51 UTC, hobinjk-ptc commented on package-lock.json
No, it looks like this properly reflects the addition of `@azure/openai` to the dependencies

2024-04-12 18:45 UTC, hobinjk-ptc approved these changes

2024-04-12 20:09 UTC, benptc approved these changes
Great start – LGTM for now. Looks like this is a construction zone and there's plenty of work that can still be done, but it's cleanly contained in routers/ai.js so that should be fine for now.

2024-04-15 19:31 UTC, merged